#!/bin/bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# USERCONFIG set after player selection below
VOLUMIOCONFIG="/boot/volumioconfig.txt"
LOGDIR="/var/log/pixis"
MARKER="/tmp/pixis/volumio-lcd.reboot-required"

log() {
  echo "[volumio-lcd] $*"
}

require_file() {
  [ -f "$1" ] || {
    echo "Missing required file: $1" >&2
    exit 1
  }
}

ensure_line() {
  local line="$1"
  local file="$2"
  touch "$file"
  grep -qxF "$line" "$file" || echo "$line" >> "$file"
}

# ── Player selection ──────────────────────────────────────────
echo ""
echo "  PIXIS Installer"
echo "  ───────────────"
echo "  Which audio player are you using?"
echo "  [1] Volumio"
echo "  [2] moOde"
echo ""
read -rp "  Enter 1 or 2: " _player_choice

case "$_player_choice" in
  1) PLAYER="volumio" ;;
  2) PLAYER="moode"   ;;
  *)
    echo "Invalid selection. Please run the installer again and enter 1 or 2." >&2
    exit 1
    ;;
esac

log "Player selected: $PLAYER"
if [ "$PLAYER" = "moode" ]; then USERCONFIG="/boot/firmware/config.txt"; else USERCONFIG="/boot/userconfig.txt"; fi
# ─────────────────────────────────────────────────────────────

for f in \
  "$ROOT/systemd/pixis-installer.service" \
  "$ROOT/systemd/volumio-lcd@.service" \
  "$ROOT/scripts/pixis-installer.sh" \
  "$ROOT/scripts/PiInstaller.sh" \
  "$ROOT/config/userconfig.txt" \
  "$ROOT/config/volumioconfig.txt" \
  "$ROOT/waveshare-2.8/Python/LCD_2inch8.py" \
  "$ROOT/waveshare-2.8/Python/${PLAYER}_lcd.py"
do
  require_file "$f"
done

install -d /etc/systemd/system
install -d /usr/local/sbin
install -d /usr/local/bin
install -d /boot
install -d "$LOGDIR"
install -d /tmp/pixis
install -d /home/${SUDO_USER:-volumio}/waveshare-2.8/Python

install -m 0644 "$ROOT/systemd/pixis-installer.service" /etc/systemd/system/pixis-installer.service
install -m 0644 "$ROOT/systemd/volumio-lcd@.service" /etc/systemd/system/volumio-lcd@.service
install -m 0755 "$ROOT/scripts/pixis-installer.sh" /usr/local/sbin/pixis-installer.sh
install -m 0755 "$ROOT/scripts/PiInstaller.sh" /usr/local/bin/PiInstaller.sh

cp -a "$ROOT/waveshare-2.8/." /home/${SUDO_USER:-volumio}/waveshare-2.8/
chown -R ${SUDO_USER:-volumio}:${SUDO_USER:-volumio} /home/${SUDO_USER:-volumio}/waveshare-2.8 || true

cp -f "$ROOT/config/userconfig.txt" "$USERCONFIG"
cp -f "$ROOT/config/volumioconfig.txt" "$VOLUMIOCONFIG"

ensure_line 'dtparam=spi=on' "$USERCONFIG"
ensure_line 'dtoverlay=spi-spidev' "$USERCONFIG"

# ── Write config.py with selected player ──────────────────────
cat > /home/${SUDO_USER:-volumio}/waveshare-2.8/Python/config.py <<EOF
# Auto-generated by PIXIS installer — do not edit manually
PLAYER = "$PLAYER"
EOF
log "config.py written with PLAYER=$PLAYER"
cat > /home/${SUDO_USER:-volumio}/waveshare-2.8/Python/config.env <<EOF
PLAYER=$PLAYER
EOF
log "config.env written with PLAYER=$PLAYER"
# ─────────────────────────────────────────────────────────────

export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y python3-pil python3-spidev python3-gpiozero
apt-get install -y python3-numpy || true

systemctl daemon-reload

if [ ! -e /dev/spidev0.0 ]; then
  log "SPI device /dev/spidev0.0 not present. Boot config updated; reboot required before enabling volumio-lcd@.service."
  date >> "$LOGDIR/installer.log"
  echo "PIXIS staged install completed; reboot required for SPI" >> "$LOGDIR/installer.log"
  touch "$MARKER"
  touch "$LOGDIR/installer.done"
  exit 0
fi
systemctl enable volumio-lcd@${SUDO_USER:-volumio}.service
systemctl restart volumio-lcd@${SUDO_USER:-volumio}.service

date >> "$LOGDIR/installer.log"
echo "PIXIS staged install completed" >> "$LOGDIR/installer.log"
touch "$LOGDIR/installer.done"
