#!/bin/bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

USERCONFIG="/boot/userconfig.txt"
LOGDIR="/var/log/pixis"
MARKER="/tmp/pixis/volumio-lcd.reboot-required"
PLAYER="volumio"
SERVICE="volumio-lcd"'@'"volumio.service"
TARGET_HOME="/home/volumio"
TARGET_PYTHON="$TARGET_HOME/waveshare-2.8/Python"

log() {
    echo "[volumio-lcd] $*"
}

require_file() {
    [ -f "$1" ] || {
        echo "Missing required file: $1" >&2
        exit 1
    }
}

ensure_line() {
    local line="$1"
    local file="$2"
    touch "$file"
    grep -qxF "$line" "$file" || echo "$line" >> "$file"
}

for f in \
    "$ROOT/systemd/pixis-installer.service" \
    "$ROOT/systemd/volumio-lcd@.service" \
    "$ROOT/scripts/pixis-installer.sh" \
    "$ROOT/scripts/PiInstaller.sh" \
    "$ROOT/waveshare-2.8/Python/LCD_2inch8.py" \
    "$ROOT/waveshare-2.8/Python/volumio_lcd.py"
do
    require_file "$f"
done

log "Installing PIXIS Volumio LCD support"

install -d /etc/systemd/system
install -d /usr/local/sbin
install -d /usr/local/bin
install -d "$LOGDIR"
install -d /tmp/pixis
install -d "$TARGET_PYTHON"

install -m 0644 \
    "$ROOT/systemd/pixis-installer.service" \
    /etc/systemd/system/pixis-installer.service

install -m 0644 \
    "$ROOT/systemd/volumio-lcd@.service" \
    /etc/systemd/system/volumio-lcd@.service

install -m 0755 \
    "$ROOT/scripts/pixis-installer.sh" \
    /usr/local/sbin/pixis-installer.sh

install -m 0755 \
    "$ROOT/scripts/PiInstaller.sh" \
    /usr/local/bin/PiInstaller.sh

cp -a "$ROOT/waveshare-2.8/." "$TARGET_HOME/waveshare-2.8/"
chown -R volumio:volumio "$TARGET_HOME/waveshare-2.8" || true

# Volumio owns /boot/volumioconfig.txt.
# PIXIS custom boot settings belong only in /boot/userconfig.txt.
ensure_line 'dtparam=spi=on' "$USERCONFIG"
ensure_line 'dtoverlay=spi-spidev' "$USERCONFIG"

# Player selection is explicit for this Volumio installer.
cat > "$TARGET_PYTHON/config.py" <<EOF_CONFIG
# Auto-generated by PIXIS installer — do not edit manually
PLAYER = "$PLAYER"
EOF_CONFIG

cat > "$TARGET_PYTHON/config.env" <<EOF_ENV
PLAYER=$PLAYER
EOF_ENV

chown volumio:volumio \
    "$TARGET_PYTHON/config.py" \
    "$TARGET_PYTHON/config.env"

log "Player configured as $PLAYER"

export DEBIAN_FRONTEND=noninteractive

apt-get update
apt-get install -y \
    python3-pil \
    python3-spidev \
    python3-gpiozero

apt-get install -y python3-numpy || true

systemctl daemon-reload

# Enable the real service instance now. If SPI requires a reboot,
# systemd will start this service automatically on the next boot.
systemctl enable "$SERVICE"

if [ ! -e /dev/spidev0.0 ]; then
    log "SPI device /dev/spidev0.0 is not present yet."
    log "Boot configuration has been updated; reboot is required."

    date >> "$LOGDIR/installer.log"
    echo "PIXIS staged install completed; reboot required for SPI" \
        >> "$LOGDIR/installer.log"

    touch "$MARKER"
    touch "$LOGDIR/installer.done"
    exit 0
fi

rm -f "$MARKER"

systemctl restart "$SERVICE"

date >> "$LOGDIR/installer.log"
echo "PIXIS Volumio LCD installation completed" \
    >> "$LOGDIR/installer.log"

touch "$LOGDIR/installer.done"

log "Installation complete"
